# Generated by Django 3.1.6 on 2021-02-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_auto_20210219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
