# Generated by Django 3.1.6 on 2021-02-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('response', '0003_auto_20210219_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_round',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('response', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.question')),
            ],
        ),
    ]
